### ISSUE TITLE
Adding additional evaluation metrics

### ISSUE THREAD

**Issue by MorenoLaQuatra** [complementizer/news-tls#3]
Hi,

First of all thanks for this great work. I want just to ask you if is it possible to add additional evaluation metrics (based on tilse) such as `agreement-based` and `concat`. Those results have been reported by original tilse paper ([paper](https://arxiv.org/pdf/1810.07949.pdf) at page 8).

Thanks,

Moreno La Quatra

**Comment by complementizer** [comment]
Thanks for the feedback!

The metric can be changed [here](https://github.com/complementizer/news-tls/blob/b79c0d1c32263d685570b326f36e35d02b292c21/experiments/evaluate.py#L76)  in the evaluation script, you can see the available metrics [here](https://github.com/complementizer/news-tls/blob/b79c0d1c32263d685570b326f36e35d02b292c21/experiments/evaluate.py#L10-L23). I'll try to make this more convenient though, e.g. picking multiple metrics of interest before running the script.

**Comment by MorenoLaQuatra** [comment]
Thank you for the comment.
